version: '2'
services:
  jod:
    image: processoeletronico/vagrant_sei4_jod:${ENVIRONMENT_VERSION}
    container_name: jod

  smtp:
    image: processoeletronico/vagrant_sei4_mailcatcher:${ENVIRONMENT_VERSION}
    ports:
      - "1080:1080"

  memcached:
    image: processoeletronico/vagrant_sei4_memcached:${ENVIRONMENT_VERSION}
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    volumes:
      - ${DATABASE_TYPE}:${DATABASE_DATA_DIR}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  solr:
    image: processoeletronico/vagrant_sei4_solr:${ENVIRONMENT_VERSION}
    ports:
      - "8983:8983"

  httpd:
    image: processoeletronico/vagrant_sei4_httpd:${ENVIRONMENT_VERSION}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .modulo.env
    ports:
      - "80:8000"
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./src:/opt/sei/web/modulos/protocolo-integrado
      - ./src/scripts:/opt/sei/scripts/mod-protocolo-integrado
      - ./src/scripts:/opt/sip/scripts/mod-protocolo-integrado
      - ./src/config:/opt/sei/config/mod-protocolo-integrado
      - ./src/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php
      - ./src/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php
      - .:/project
    environment:
      - LANG=pt_BR.ISO-8859-1
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - HOST_URL=${SEI_HOST}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_CHAVE_ACESSO=${SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}

      - SIP_CHAVE_ACESSO=${SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod

volumes:
  MySql:
  Oracle:
  SqlServer: